### ISSUE TITLE
Specific version to languages

### ISSUE THREAD

**Issue by marioidival** [polyglotness/polyglotness#7]
Hello, 

I have a doubt about versions of languages. On [README](https://github.com/polyglotness/polyglotness/blob/master/python/README.md) of Python folder, has a link to documentation of version 2, but I want use Python 3 to doing this task's.

**Comment by ellisonleao** [comment]
You can use Python 3 for the tasks, as long as the tests can pass into the future specs we will provide #8 . I will add  some python 3 links there as well, thanks for the report!

**Comment by ellisonleao** [comment]
https://github.com/polyglotness/polyglotness/tree/master/python

Python 3 docs added
